name: guardian-fe-cicd

on:
  push:
    branches: 
      - prod
  pull_request:
    branches:    
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Output build variables
      run: echo 'wisheshk/${{ github.event.repository.name }}-prod:$(date +%s)'

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: wisheshk/${{ github.event.repository.name }}-prod:$(date +%s)
    
    
